# Generated by Django 5.2.7 on 2025-10-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="anos_disponiveis",
            field=models.ManyToManyField(
                blank=True, related_name="disciplinas", to="resumos.ano"
            ),
        ),
    ]
