# Generated by Django 5.2.7 on 2025-11-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumos", "0002_disciplina_anos_disponiveis"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                ("cor", models.CharField(default="#6c757d", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Tags",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="resumo",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="resumos", to="resumos.tag"
            ),
        ),
    ]
