# Generated by Django 5.2.9 on 2025-12-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumos", "0003_tag_resumo_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resumo",
            name="arquivo",
        ),
        migrations.AddField(
            model_name="resumo",
            name="ficheiro",
            field=models.FileField(default="", upload_to="resumos/"),
            preserve_default=False,
        ),
    ]
