# Generated by Django 6.0.2 on 2026-03-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumos", "0005_emailverificationtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_email",
                    models.EmailField(
                        blank=True,
                        help_text="Endereço que irá receber notificações quando novos utilizadores ou resumos precisarem de aprovação.",
                        max_length=254,
                        verbose_name="Email para notificações de verificação",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuração de Verificação",
                "verbose_name_plural": "Configurações de Verificação",
            },
        ),
        migrations.AddField(
            model_name="resumo",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
